Create Database WINFORM_DB;

USE WINFORM_DB;

SELECT * FROM LOGIN_TBL

CREATE TABLE LOGIN(	/*This table will be used which will store and compare login/signup details. */
	USERNAME VARCHAR(20) NOT NULL,
	PASS NVARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) 
	);

CREATE TABLE SAMSUNG(	/*This table will be used which will store and compare login/signup details. */
	BRAND VARCHAR(20) NOT NULL,
	MODEL VARCHAR(50) NOT NULL,
	SIZE VARCHAR(50) NOT NULL,
	RAM VARCHAR(50) NOT NULL,
	STORAGE VARCHAR(50) NOT NULL,
	OPERATING_SYSTEM VARCHAR(50) NOT NULL,
	MEGAPIXELS VARCHAR (50) NOT NULL,
	PRICE VARCHAR(50) NOT NULL
	);
SELECT BRAND FROM SAMSUNG WHERE MODEL = 'GALAXY S21'; 
DELETE SAMSUNG

INSERT INTO SAMSUNG VALUES
('SAMSUNG','GALAXY S20' , '8GB', '128GB','ANDROID 10', '64MP','6.2 INCHES','200000');
INSERT INTO SAMSUNG VALUES
('SAMSUNG','GALAXY S21' , '12GB', '128GB','ANDROID 10', '64MP', '6.3 INCHES','160000');
INSERT INTO SAMSUNG VALUES
('SAMSUNG','GALAXY S10' , '8GB', '64GB','ANDROID 9', '32MP', '6.1 INCHES','100000');
INSERT INTO SAMSUNG VALUES
('SAMSUNG','GALAXY S9' , '8GB', '64GB','ANDROID 9', '32MP', '6.2 INCHES','90000');
INSERT INTO SAMSUNG VALUES
('SAMSUNG','GALAXY S8' , '6GB', '64GB','ANDROID 8', '32MP', '6.0 INCHES','70000');
INSERT INTO SAMSUNG VALUES	
('SAMSUNG','GALAXY S7' , '4GB', '32GB','ANDROID 7', '32MP', '6.0 INCHES','60000');
INSERT INTO SAMSUNG VALUES
('SAMSUNG','GALAXY S6' , '4GB', '32GB','ANDROID 7', '12MP', '6.1 INCHES','40000');
INSERT INTO SAMSUNG VALUES
('SAMSUNG','GALAXY S5' , '2GB', '16GB','ANDROID 6', '12MP', '6.1 INCHES','30000');
INSERT INTO SAMSUNG VALUES
('SAMSUNG','GALAXY S4' , '2GB', '16GB','ANDROID 5', '8MP', '5.2 INCHES','20000');
SELECT * FROM SAMSUNG

ALTER TABLE SAMSUNG
DROP COLUMN SIZE;

select * from SAMSUNG


CREATE TABLE APPLE(	/*This table will be used which will store and compare login/signup details. */
	BRAND VARCHAR(20) NOT NULL,
	MODEL VARCHAR(50) NOT NULL,
	RAM VARCHAR(50) NOT NULL,
	STORAGE VARCHAR(50) NOT NULL,
	OPERATING_SYSTEM VARCHAR(50) NOT NULL,
	MEGAPIXELS VARCHAR (50) NOT NULL,
	DISPLAY VARCHAR(50) NOT NULL,
	PRICE VARCHAR(50) NOT NULL
	);
	DELETE APPLE


INSERT INTO APPLE VALUES
('APPLE','iphone 12' , '4GB', '128GB','IOS 14', '24MP','6.1 INCHES','300000');
INSERT INTO APPLE VALUES
('APPLE','iphone 11' , '4GB', '128GB','IOS 13', '24MP','6.1 INCHES','200000');
INSERT INTO APPLE VALUES
('APPLE','iphone X' , '4GB', '128GB','IOS 12', '20MP','6.1 INCHES','120000');
INSERT INTO APPLE VALUES
('APPLE','iphone 8' , '3GB', '128GB','IOS 11', '18MP','5.7 INCHES','80000');
INSERT INTO APPLE VALUES
('APPLE','iphone 7' , '2GB', '64GB','IOS 11', '16MP','5.5 INCHES','70000');
INSERT INTO APPLE VALUES
('APPLE','iphone 6' , '2GB', '64GB','IOS 10', '14MP','6 INCHES','50000');
INSERT INTO APPLE VALUES
('APPLE','iphone 5' , '1GB', '32GB','IOS 8', '12MP','5.7 INCHES','30000');
INSERT INTO APPLE VALUES
('APPLE','iphone 4' , '1GB', '16GB','IOS 6', '10MP','4.7 INCHES','200000');
INSERT INTO APPLE VALUES
('APPLE','iphone 3' , '1GB', '8GB','IOS 3', '8MP',' 4 INCHES','10000');

DROP TABLE SAMSUNG

SELECT * FROM ONEPLUS

INSERT INTO ONEPLUS VALUES
('ONEPLUS','NORD' , '12GB', '128','ANDROID 10', '48MP','6.4 INCHES','69000');
INSERT INTO ONEPLUS VALUES
('ONEPLUS','8T' , '8GB', '64','ANDROID 9', '40MP','6.2 INCHES','59000');
INSERT INTO ONEPLUS VALUES
('ONEPLUS','6T' , '6GB', '64','ANDROID 8.1', '32MP','6.0 INCHES','49000');
INSERT INTO ONEPLUS VALUES
('ONEPLUS','5T' , '4GB', '32','ANDROID 7.1', '30MP','5.8 INCHES','39000');
INSERT INTO ONEPLUS VALUES
('ONEPLUS','3T' , '4GB', '16','ANDROID 7.1', '24MP','5.2 INCHES','29000');
INSERT INTO ONEPLUS VALUES
('ONEPLUS','X' , '2GB', '16','ANDROID 6', '20MP','5.0 INCHES','19000');
INSERT INTO ONEPLUS VALUES
('ONEPLUS','ONE' , '3GB', '8','ANDROID 5', '18MP','4.8 INCHES','15000');
INSERT INTO ONEPLUS VALUES
('ONEPLUS','MCLAREN' , '8GB', '128','ANDROID 4', '16MP','4.6 INCHES','73000');

CREATE TABLE ONEPLUS(	/*This table will be used which will store and compare login/signup details. */
	BRAND VARCHAR(20) NOT NULL,
	MODEL VARCHAR(50) NOT NULL,
	RAM VARCHAR(50) NOT NULL,
	STORAGE VARCHAR(50) NOT NULL,
	OPERATING_SYSTEM VARCHAR(50) NOT NULL,
	MEGAPIXELS VARCHAR (50) NOT NULL,
	DISPLAY VARCHAR(50) NOT NULL,
	PRICE VARCHAR(50) NOT NULL
	);

SELECT * FROM APPLE

SELECT * FROM ONEPLUS

SELECT * FROM LOGIN_TBL

CREATE TABLE HUAWEI(	/*This table will be used which will store and compare login/signup details. */
	BRAND VARCHAR(20) NOT NULL,
	MODEL VARCHAR(50) NOT NULL,
	RAM VARCHAR(50) NOT NULL,
	STORAGE VARCHAR(50) NOT NULL,
	OPERATING_SYSTEM VARCHAR(50) NOT NULL,
	MEGAPIXELS VARCHAR (50) NOT NULL,
	DISPLAY VARCHAR(50) NOT NULL,
	PRICE VARCHAR(50) NOT NULL
	);

	SELECT * FROM HUAWEI

	DROP TABLE HUAWEI



INSERT INTO HUAWEI VALUES
('HUAWEI','NOVA 8','8GB', '128GB','Android 10', '64MP','6.53 inches','80000');
INSERT INTO HUAWEI VALUES
('HUAWEI','MATE 40' ,'8GB', '256GB','Android 10', '50MP','6.5 inches','155000');
INSERT INTO HUAWEI VALUES
('HUAWEI','ENJOY 20' ,'6GB', '128GB','Android 10', '13MP','6.6 inches','90000');
INSERT INTO HUAWEI VALUES
('HUAWEI','NOVA 7' ,'8GB', '128GB','Android 10', '48MP','6.4 inches','117000');
INSERT INTO HUAWEI VALUES
('HUAWEI','P40' ,'6GB', '128GB','Android 10', '50MP','6.1 inches','123000');
INSERT INTO HUAWEI VALUES
('HUAWEI','NOVA 6' ,'8GB', '128GB','Android 10', '40MP','6.57 inches','78000');
INSERT INTO HUAWEI VALUES
('HUAWEI','Y9' ,'6GB', '128GB','Android 9', '48MP','6.59 inches','110000');
INSERT INTO HUAWEI VALUES
('HUAWEI','ENJOY 10' ,'4GB', '64GB','Android 9', '48MP','6.3 inches','77000');
INSERT INTO HUAWEI VALUES
('HUAWEI','NOVA 5' ,'8GB', '128GB','Android 9', '48MP','6.3 inches','70000')

CREATE TABLE BLACKBERRY(	/*This table will be used which will store and compare login/signup details. */
	BRAND VARCHAR(20) NOT NULL,
	MODEL VARCHAR(50) NOT NULL,
	RAM VARCHAR(50) NOT NULL,
	STORAGE VARCHAR(50) NOT NULL,
	OPERATING_SYSTEM VARCHAR(50) NOT NULL,
	MEGAPIXELS VARCHAR (50) NOT NULL,
	DISPLAY VARCHAR(50) NOT NULL,
	PRICE VARCHAR(50) NOT NULL
	);

DROP TABLE BLACKBERRY
SELECT * FROM BLACKBERRY 

INSERT INTO BLACKBERRY VALUES
('BLACKBERRY','KEY2' , '6GB' , '128GB','Android 8.1', '12MP','4.5 inches','99000');
INSERT INTO BLACKBERRY VALUES
('BLACKBERRY','EVOLVE X' , '6GB', '64GB','Android 8.1', '13MP','6 inches','67000');
INSERT INTO BLACKBERRY VALUES
('BLACKBERRY','MOTION' ,'4GB', '32GB','Android 7.1', '12MP','5.5 inches','52000');
INSERT INTO BLACKBERRY VALUES
('BLACKBERRY','AURORA' ,'6GB', '64GB','Android 8.1', '13MP','6 inches','28900');
INSERT INTO BLACKBERRY VALUES
('BLACKBERRY','KEYONE' ,'4GB', '64GB','Android 7.1', '12MP','4.5 inches','55490');
INSERT INTO BLACKBERRY VALUES
('BLACKBERRY','PRIV' ,'3GB', '32GB','Android 5.1.1', '18MP','5.4 inches','44000');
INSERT INTO BLACKBERRY VALUES
('BLACKBERRY','PORSHE DESIGN' ,'12GB', '256GB','Android 10', '50MP','6.76 inches','55650');
INSERT INTO BLACKBERRY VALUES
('BLACKBERRY','PASSPORT' ,'3GB', '32GB','Android 10.3', '13MP','4.5 inches','22900');
INSERT INTO BLACKBERRY VALUES
('BLACKBERRY','Z3' ,'1.5GB', '8GB','Android 10.2.1', '5MP','5.0 inches','13000');

select * from BLACKBERRY

CREATE TABLE ADDRESS_INFO(	/*This table will be used which will store and compare login/signup details. */
	HOUSE_NO VARCHAR(20) NOT NULL,
	STREET_NAME VARCHAR(50) NOT NULL,
	AREA_NAME VARCHAR(50) NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
	);
	SELECT * FROM ADDRESS_INFO;

CREATE TABLE INFO(	/*This table will be used which will store and compare login/signup details. */
	HOUSE_NO VARCHAR(20) NOT NULL,
	STREET_NAME VARCHAR(50) NOT NULL,
	AREA_NAME VARCHAR(50) NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
	FULL_NAME VARCHAR(20) NOT NULL,
	CONTACT_NUMBER VARCHAR(50) NOT NULL,
	EMAIL_ID VARCHAR(50) NOT NULL,

	);
	DROP TABLE PERSONAL_INFO
	SELECT * FROM PERSONAL_INFO
